plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - "sorbet/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "benchmark/fixtures/**/*"
    - "benchmark/**/*.rb"

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"

Sorbet/FalseSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"

Sorbet/StrictSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/ApplicationRecord:
  Enabled: false

Rails/ApplicationJob:
  Enabled: false

Rails/Delegate:
  Enabled: false

Sorbet/ObsoleteStrictMemoization:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
