# typed: strict
# frozen_string_literal: true

require "sorbet-runtime"
require "active_record"
require "active_support/concern"
require "active_support/core_ext/string/inflections"
require "active_support/core_ext/module/delegation"
require "active_support/core_ext/integer/time"
require "active_support/core_ext/object/blank"
require "securerandom"

require_relative "../activerecord_materialized_types"
require_relative "materialized/type_reexports"
require_relative "materialized/configuration"
require_relative "materialized/module_api"
require_relative "materialized/refresh_callbacks"
require_relative "materialized/write_change"
require_relative "materialized/maintenance_delta_builder"
require_relative "materialized/table_model_registry"
require_relative "materialized/dependency_trackable"
require_relative "materialized/dependency_registry"
require_relative "materialized/async_refresher"
require_relative "materialized/refresh_scheduler"
require_relative "materialized/registry"
require_relative "materialized/metadata_record"
require_relative "materialized/view_incremental_class_methods"
require_relative "materialized/view_refresh_policy_class_methods"
require_relative "materialized/view_configuration_class_methods"
require_relative "materialized/view_query_access_class_methods"
require_relative "materialized/view"
require_relative "materialized/view_class"
require_relative "materialized/refresh_result"
require_relative "materialized/refresher"
require_relative "materialized/maintenance_delta"
require_relative "materialized/view_definition"
require_relative "materialized/query_expressions"
require_relative "materialized/cache_table_schema"
require_relative "materialized/migration_builder"
require_relative "materialized/schema_verifier"
require_relative "materialized/cold_read"
require_relative "materialized/relation_cache_writer"
require_relative "materialized/maintenance_store"
require_relative "materialized/incremental_maintainer"
require_relative "materialized/metadata"
require_relative "materialized/partition_record"
require_relative "materialized/partition_state"

require_relative "materialized/refresh_job" if defined?(ActiveJob::Base)

require_relative "materialized/railtie" if defined?(Rails::Railtie)
