# frozen_string_literal: true

require "active_record"
require "active_support/concern"
require "active_support/core_ext/string/inflections"
require "active_support/core_ext/module/delegation"
require "active_support/core_ext/integer/time"
require "active_support/core_ext/object/blank"
require "securerandom"

require_relative "materialized/change_source"
require_relative "materialized/configuration"
require_relative "materialized/configurable_table_name"
require_relative "materialized/connection_routing"
require_relative "materialized/module_api"
require_relative "materialized/refresh_callbacks"
require_relative "materialized/write_change"
require_relative "materialized/debezium_envelope"
require_relative "materialized/instrumentation"
require_relative "materialized/maintenance_delta_builder"
require_relative "materialized/write_maintenance"
require_relative "materialized/table_model_registry"
require_relative "materialized/dependency_trackable"
require_relative "materialized/dependency_registry"
require_relative "materialized/async_refresher"
require_relative "materialized/refresh_scheduler"
require_relative "materialized/registry"
require_relative "materialized/metadata_record"
require_relative "materialized/view_incremental_class_methods"
require_relative "materialized/view_refresh_policy_class_methods"
require_relative "materialized/view_configuration_class_methods"
require_relative "materialized/view_query_access_class_methods"
require_relative "materialized/view"
require_relative "materialized/refresh_result"
require_relative "materialized/refresher"
require_relative "materialized/maintenance_delta"
require_relative "materialized/partition_filter"
require_relative "materialized/view_definition"
require_relative "materialized/aggregate_analysis"
require_relative "materialized/summary_delta"
require_relative "materialized/summary_delta_builder"
require_relative "materialized/query_expressions"
require_relative "materialized/cache_table_schema"
# must follow cache_table_schema: aliases its ColumnDefinition at load time
require_relative "materialized/column_type_inference"
require_relative "materialized/migration_builder"
require_relative "materialized/schema_verifier"
require_relative "materialized/data_verification_result"
require_relative "materialized/partition_snapshot"
require_relative "materialized/data_verifier"
require_relative "materialized/cold_read"
require_relative "materialized/read_router"
require_relative "materialized/table_swap"
require_relative "materialized/relation_cache_writer"
require_relative "materialized/maintenance_store"
require_relative "materialized/incremental_maintainer"
require_relative "materialized/incremental_refresh"
require_relative "materialized/delta_maintainer"
require_relative "materialized/metadata"
require_relative "materialized/reconcile_result"
require_relative "materialized/reconciler"
require_relative "materialized/partition_record"
require_relative "materialized/partition_state"
require_relative "materialized/source_watermark_record"
require_relative "materialized/source_watermark"
require_relative "materialized/write_outbox_record"
require_relative "materialized/write_outbox"

if defined?(ActiveJob::Base)
  require_relative "materialized/refresh_job"
  require_relative "materialized/reconcile_job"
end

require_relative "materialized/railtie" if defined?(Rails::Railtie)
